name: CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cabextract
        docker run --rm --privileged hypriot/qemu-register
    - name: Build image
      run: make ${GITHUB_REF##*/}
    - name: Push image
      run: |
        docker login --username connorworley --password '${{ secrets.DOCKER_HUB_PASSWORD }}'
        docker push firstrustcompetition/cross:${GITHUB_REF##*/}
